### ISSUE TITLE
Windows Installer - Improvements

### ISSUE THREAD

**Issue by bovirus** [philipbutkiewicz/SharpCut#2]
@philipbutkiewicz 

Recently you relased a new installer version (1.4.8.0).

I found some issues

On top left no info about version
![image](https://github.com/user-attachments/assets/1c38bebc-5e02-4f8c-8153-69f3bcde50c7)

On file propoerteis no info about versiuon.
![image](https://github.com/user-attachments/assets/32d14be8-7d5d-478d-a16d-06a415afdadb)

How can help you about it?

**Comment by philipbutkiewicz** [comment]
Hi, it seems that indeed the installer doesn't have any version info. I'm afraid I don't know why that would be. I'll take a look at it when I can but if you know your way around InnoSetup you can find the install script here:
https://github.com/philipbutkiewicz/SharpCut/blob/main/SharpCut.iss

**Comment by bovirus** [comment]
@philipbutkiewicz 

Fixes

Original:
#define MyAppVersion             GetVersionNumbersString('SharpCut\SharpCut\bin\x64\Release\SharpCut.exe')

Right
#define MyAppVersion             GetVersionNumbersString('SharpCut\bin\x64\Release\SharpCut.exe')

Please approve PR (https://github.com/philipbutkiewicz/SharpCut/pull/3)

Please rebuild the installer and test.

Note; when I edited .iss file I got this warning

![image](https://github.com/user-attachments/assets/4ca26173-42b6-4529-b8c4-c63dbdbc5003)

Thanks.

**Comment by philipbutkiewicz** [comment]
Verified. Next version will have a new installer build.
