### ISSUE TITLE
Batch Merge is missing multi-language translation character resource files

### ISSUE THREAD

**Issue by wcxu21** [philipbutkiewicz/SharpCut#7]
Hi
Batch Merge lacks multi-language translation character resource files. Can you add multi-language support?

Another question is that in the "Insert Split" button in the main interface, the Chinese characters are truncated because the button is too small. Currently, only three can be displayed. It is recommended that you increase the size of the button character display.

![image](https://github.com/user-attachments/assets/25a6f22b-f438-4c8b-b94a-4aa851a9dd39)

The layout of the window may cause some characters to be truncated. It is recommended that you try to rearrange the window.

![QQ_1733276865779](https://github.com/user-attachments/assets/fd10aef4-406c-4b6e-be81-06586601286a)

Thank you.

**Comment by philipbutkiewicz** [comment]
Done. :)
